name: Release Nightly

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    runs-on: macos-11.0
    name: Release Nightly
    permissions:
      contents: write
      discussions: write

    env:
      CARGO_TERM_COLOR: always
      GITHUB_REPOSITORY: raphamorim/rio
      RUST_BACKTRACE: full
      TAG: nightly
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: rustup toolchain install stable --profile minimal
      - run: rustup target add x86_64-apple-darwin aarch64-apple-darwin
      - run: make release-macos
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: 'nightly-${{ github.sha }}'
          tag_prefix: ''
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release nightly
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          name: nightly
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            release/macos-rio.zip
            LICENSE
